# Generated by Django 5.1.7 on 2025-03-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critiq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
